name: Development

on:
# add a push event that triggers this workflow
# on every push to the master branch
  push:
    branches:
      - main

jobs:
  build-test:
  # add a build server of ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:
    # add a new step to checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    # add a new steop to install .Net SDK 7
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    # add a new steop to restore nuget packages
    - name: Restore NuGet Packages
      run: dotnet restore


    # add a new step to build the entire solution with Release configuration
    - name: Build
      run: dotnet build --configuration Release

    # add a new step to tes the solution with Release configuration
    - name: Test
      run: dotnet test --configuration Release

    # add a new step to publish src/WebApi with Release configuration
    - name: Publish
      run: dotnet publish src/WebApi --configuration Release --output ./publish

